[project]
name = "python-gcode"
version = "0.1.0"
description = "Parse and manipulate 3D printer Gcode files"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gcode-geom",
    "rich>=13.8.1",
]

# Tell the build system to find packages under the 'src' directory
packages = [{include = "python_gcode", from = "src"}]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.ruff.lint]
ignore = [
	"E101",   #Mixed spaces & tabs
	"E401",   #Multiple imports on a line
	"E501",   #Too-long lines
	"E701",   #Multiple statements on a line
	"E741",   #Ambiguous variable names
]

[tool.uv.sources]
gcode-geom = { git = "https://github.com/fetlab/gcode_geom" }
